#!/bin/bash
gcloud auth activate-service-account --key-file /root/.gcp/terraform_sa.json 
gcloud config set project ${GCP_PROJECT}
echo Deleting velostrata instances... 
gcloud compute instances list | grep 'velostrata-edge\|wordpress' | awk '{printf "gcloud compute instances delete %s --zone %s -q", $1, $2}' | bash 
echo Deleting addresses ... 
gcloud compute addresses list | grep 'velostrata-edge\|wordpress' | awk '{printf "gcloud compute addresses delete %s --region %s -q", $1, $5}' | bash 
echo deleting aws instance... 
aws ec2 describe-instances --filter "Name=tag:Name,Values=Velostrata*" "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].InstanceId" --region ap-southeast-1 | awk '{if(NR==2) printf "aws ec2 terminate-instances --instance-ids %s --region ap-southeast-1", $0}' | bash	